### ISSUE TITLE
Creating a new plugin with npm init does not work on Windows

### ISSUE THREAD

**Issue by Christian24** [dtsgenerator/create#2]
Hello,

The docs state that a new plugin can be created using `npm init` like so: `npm init @dtsgenerator plugin-name`

However, this does not work on my machine (recent npm and Windows 10). Here is the log: 
````
PS C:\Users\Chris\Documents> npm init @dtsgenerator plugin-name
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/create-plugin-name - Not found
npm ERR! 404
npm ERR! 404  'create-plugin-name@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Chris\AppData\Roaming\npm-cache\_logs\2020-07-13T18_58_20_938Z-debug.log
Install for create-plugin-name@latest failed with code 1
````

If I am not mistaken this should work according to the npm docs: https://docs.npmjs.com/cli/init#description

Maybe it is a bug with npm? Does this work on other platforms? 

However, using `npx` to create a new plugin works fine. It might be useful to mention this in the README for `dtsgenerator`.

Thanks,
Christian

**Comment by horiuchi** [comment]
What are you using the npm version?

Please retry it after updating npm. `npm install -g npm`

**Comment by Christian24** [comment]
That was my first idea too. I had already tried that. Version is 6.14.6 is the one I have and it is the latest. Maybe another Windows problem? :)

**Comment by horiuchi** [comment]
hmmm...
Probably it's just a problem in the Windows environment only. 😢
